
swagger: "2.0"
info:
  title: City Guide Media Service API
  description: Node And Resource API
  version: 0.0.2
host: api.12301.io
basePath: /v1/media-service
schemes:
  - http
produces:
  - application/json
consumes:
  - application/json
paths:
  /node:
    post:
      description: 创建节点
      parameters:
        - name: nodes 
          in: body
          description: 创建节点参数
          required: true
          schema:
            type: array
            description: 节点参数
            items:
              $ref: "#/definitions/CreateNodeParameter"
      responses:
        200:
          description: OK
    delete:
      description: 删除节点
      parameters:
        - name: ids 
          in: body
          description: 删除节点参数
          required: true
          schema:
            type: array
            description: 节点ID参数
            items:
              type: string
              description: 节点ID
      responses:
        200:
          description: OK
    put:
      description: 修改节点
      parameters:
        - name: nodes 
          in: body
          description: 修改节点参数(只修改传入的参数)
          required: true
          schema:
            type: array
            description: 节点参数(只修改传入的参数)
            items:
              $ref: "#/definitions/UpdateNodeParameter"
      responses:
        200:
          description: OK
    get:
      description: 通过id或path获取节点信息
      parameters:
        - name: id 
          in: query 
          type: string
          description: 节点ID
        - name: path 
          in: query
          type: string
          description: 节点路径
      responses:  
        200:
          description: OK
          schema:
            $ref: "#/definitions/Node"
  /node/{node-id}/children:
    get:
      description: 查找子节点
      parameters:
        - $ref: "#/parameters/node-id"
      responses:
        200:
          description: OK
          schema:
            type: array
            description: 子节点
            items:
              $ref: "#/definitions/Node"
  /resource:
    post:
      description: 创建资源
      parameters:
        - name: resources
          in: body
          description: 资源参数
          required: true
          schema:
            type: array
            description: 资源
            items:
              $ref: "#/definitions/CreateResourceParameter"
      responses:
        200:
          description: OK
    delete:
      description: 删除资源
      parameters:
        - name: ids 
          in: body
          required: true
          schema:
            type: array
            description: 删除资源参数
            items:
              type: string 
              description: 资源ID
      responses:
        200:
          description: OK
    put:
      description: 修改资源
      parameters:
        - name: nodes 
          in: body
          description: 修改资源参数
          required: true
          schema:
            type: array
            description: 资源(只修改传入的参数)
            items:
              $ref: "#/definitions/UpdateResourceParameter"
      responses:
        200:
          description: OK
    get:
      description: 查找资源
      parameters:
        - name: nodeId 
          in: query
          description: 所属节点ID
          type: string
        - name: type
          in: query
          description: 资源类型
          type: integer
          format: int32
        - name: name
          in: query
          description: 资源名称
          type: string
        - name: tag
          in: query
          description: 资源标签
          type: string
        - name: startTime
          in: query
          description: 开始时间如:yyyy-MM-dd
          type: string
          format: date-time
        - name: endTime
          description: 结束时间如:yyyy-MM-dd
          in: query
          type: string
          format: date-time
        - name: offset
          description: 分页查询的起始位置(不传该参数默认查询从0开始)
          in: query
          type: integer
          format: int32
        - name: limit
          description: 查询的条数(不传该参数默认返回10条)
          in: query
          type: integer
          format: int32
      responses:
        200:
          description: OK
          schema:
            type: array
            description: 资源
            items:
              $ref: "#/definitions/Resource"
  /res: 
    get:
      description: 查找单一资源
      parameters:
        - $ref: "#/parameters/res-id"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Resource"
  /res-upload:
    get:
      summary: 初始化分片上传
      description: 通过文件路径和类型初始化一个上传
      parameters:
        - name: path 
          required: true
          in: query
          description: 文件上传对应路径值，含文件名(如:北京/奥林匹克公园/123.jpg,节点关系用/来隔开)
          type: string
        - name: contenttype
          required: true
          in: query
          description: 文件的格式(1:文本类型 2:图片类型 3:音频类型 4:视频文件 5:其他)
          type: string
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/InitUploadResult"
    post:
      summary: 完成分片上传
      description: 通过etag将上传的分片进行合并
      parameters:
        - name: finishUploadParameters
          in: body
          description: 完成分片合并对应参数
          required: true
          schema:
            type: object
            description: 合并参数
            $ref: "#/definitions/FinishUploadParameter"
      responses:
        200:
          description: OK
          schema:
            type: object
            description: 资源
            $ref: "#/definitions/FinishUploadResult"        
    delete:
      summary: 放弃分片上传(暂不可用)
      description: 通过uploadId和key取消一个上传
      parameters:
        - name: uploadId 
          in: query
          description: 取消上传的uploadId
          type: string
      responses:
        200:
          description: OK
  /res-upload-status:
    get:
      summary: 获取上传是否失效
      description: 通过uploadId获取该次上传是否可以续传
      parameters:
        - name: uploadId
          in: query
          required: true
          description: 上传的uploadId
          type: string
      responses:
        200:
          description: ok
          schema:
            type: integer
            format: int32
            description: (就绪状态表示可以续传)0:就绪 1:已完成 2:已放弃 3:已过期
definitions:
  Node:
    type: object
    description: 节点
    properties:
      id:
        type: string
        description: id
      name:
        type: string
        description: 名称
      parentId: 
        type: string
        description: 父节点id
      path:
        type: string 
        description: 路径(不包含根节点)
      createTime:
        type: string
        format: date-time
        description: 创建时间
  CreateNodeParameter:
    type: object
    description: 参数
    properties:
      name:
        type: string
        description: 名称
      parentId:
        type: string
        description: 父节点id
      path:
        type: string
        description: 节点的路径
  UpdateNodeParameter:
    type: object
    description: 参数
    properties:
      id:
        type: string
        description: id
      name:
        type: string
        description: 名称
      parentId:
        type: string
        description: 父节点id
      path:
        type: string
        description: 节点的路径
  Resource:
    type: object
    description: 资源
    properties:
      id:
        type: string
        description: id
      nodeId:
        type: string
        description: nodeId
      name:
        type: string
        description: 名称
      type:
        type: integer
        format: int32
        description: 类型  
      keyWord:
        type: string
        description: keyWord
      bucket: 
        type: string
        description: 所属bucket的信息
      resourceUrl:
        type: string
        description: 资源URL
      createTime:
        type: string
        format: date-time
        description: 创建时间
  CreateResourceParameter:
    type: object
    description: 参数
    properties:
      nodeId:
        type: string
        description: 资源对应的节点ID  
      type:
        type: integer
        format: int32
        description: 资源类型(1:文本 2:图片 3:音频 4:视频)  
      name:
        type: string
        description: 资源名称
      keyWord:
        type: string
        description: 资源路径
      bucket:
        type: string
        description: 所属的bucket
      tags:
        type: array
        description: 资源标签数组
        items:
          type: string
          description: 资源标签
  UpdateResourceParameter:
    type: object
    description: 参数
    properties:
      id:
        type: string
        description: 资源ID
      nodeId:
        type: string
        description: 节点ID 
      type:
        type: integer
        format: int32
        description: 资源类型(1:文本 2:图片 3:音频 4:视频) 
      name:
        type: string
        description: 名称
      keyWord:
        type: string
        description: 资源路径 
      bucket:
        type: string
        description: 所属的bucket
      tags:
        type: array
        description: 标签数组(新的标签数据会取代以前的标签数组,没设置默认用以前的标签数组)
        items:
          type: string
          description: 标签
  InitUploadResult:
    type: object
    description: 初始化上传的返回值
    properties:
      uploadId:
        type: string
        description: 初始化返回的uploadId
      blockSize:
        type: integer
        format: int32
        description: 本次初始化的块的大小
      authorization:
        type: string
        description: 用于上传分片的签名参数
      contentType: 
        type: string
        description: 文件类型
      bucketName:
        type: string
        description: bucketName
      uploadPartUrl:
        type: string
        description: 上传分片的url
  FinishUploadParameter:
    type: object
    description: 完成上传对应的参数
    properties:
      uploadId:
        type: string
        description: 完成上传的uploadId
      etags:
        type: array
        items: 
          type: string
          description: 上传的分片对应的每一片的etag
  FinishUploadResult:
    type: object
    description: 完成分片上传的返回值
    properties:
      resourceId:
        type: string
        description: 上传完成数据库resourceId
      key:
        type: string
        description: 本次上传对应的key
      fileSize:
        type: integer
        format: int64
        description: 文件上传后的大小
      resourceUrl:
        type: string
        description: 文件url
parameters:
  node-id:
    name: node-id
    in: path
    description: 节点id
    required: true
    type: string
  res-id: 
    name: res-id
    in: query
    description: 资源id
    required: true
    type: string